nigma_local:
    resource: "@NigmaLocalBundle/Resources/config/routing.yml"
    prefix:   /

nigma_admin:
    resource: "@NigmaAdminBundle/Controller/"
    type:     annotation
    prefix:   /

nigma_content:
    resource: "@NigmaContentBundle/Resources/config/routing.yml"
    prefix:   /

nigma_common:
    resource: "@NigmaCommonBundle/Resources/config/routing.yml"
    prefix:   /

