parameters:
#    nigma_content.example.class: Nigma\ContentBundle\Example

services:
#    nigma_content.example:
#        class: %nigma_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
